### ISSUE TITLE
markup contains both "count" and "quantity"

### ISSUE THREAD

**Issue by hongcui** [biosemantics/charaparser#17]
![image](https://cloud.githubusercontent.com/assets/831423/5685429/4fc0c712-97f7-11e4-8e7a-082c2c999558.png)

**Comment by hongcui** [comment]
checked and CharaParser output only outputs 'count'. This can be fixed easily. I will fix it.

**Comment by rodenhausen** [comment]
Likely the "quantity of x at y" type columns originate from the
matrix-generation module. In a scenario where we have a relation say "with"
from "x" to "y" it will generate the "present" for "quantity of x at y".

"count of carpel" is likely directly from charaparser output

**Comment by hongcui** [comment]
fixed
